name: CD Fake
on: 
  workflow_call:
    secrets:
      ambiente:
        description: 'Ambiente de destino para o deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no ambiente
        run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"